# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and push - deck-recommender

on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  IMAGE_NAME: deck-recommender

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      #
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: "6.0.x"

      - name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.1.11

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        #
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Version handling
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            VERSION=$(echo "${GITHUB_REF#refs/tags/}" | sed -e 's/^v//')
          else
            VERSION=${{ steps.version_step.outputs.fullSemVer }}
          fi

          # Additional tag for master branch
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            ADDITIONAL_TAG=latest
          fi

          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"
          echo "SemVer=${{ steps.version_step.outputs.fullSemVer }}"

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION

          if [ -n "$ADDITIONAL_TAG" ]; then
            docker tag $IMAGE_NAME $IMAGE_ID:$ADDITIONAL_TAG
          fi

          docker push $IMAGE_ID:$VERSION

          if [ -n "$ADDITIONAL_TAG" ]; then
            docker push $IMAGE_ID:$ADDITIONAL_TAG
          fi
      - name: Trigger webhook
        run: curl -X POST 'https://${{vars.WEBHOOK_NAME}}:${{secrets.WEBHOOK_SECRET}}@hs-deck-recommender-hfhxacfxg3dedvg2.scm.westeurope-01.azurewebsites.net/api/registry/webhook'

  #   runs-on: ubuntu-latest
  #   needs: push
  #   environment:
  #     name: "Production"
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  #   permissions:
  #     id-token: write #This is required for requesting the JWT
  #     contents: read #This is required for actions/checkout

  #   steps:
  #     - name: Download artifact from build jobs
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: node-app

  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1110C749DBC04095A80049A889760D35 }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0811333F195D44DDA21FDE43949E0627 }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BFF1FADA7BD04E16A1FF08D5AE25E6E0 }}

  #     - name: "Deploy to Azure Web App"
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: "hs-deck-recommender"
  #         slot-name: "Production"
  #         package: .
